name: Docker Image CI to GHCR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancelar build previa redundante
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/eonishi/copal-front:latest
